trigger:

- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildServer
        steps:
          - checkout: self
          - task: NodeTool@0
            displayName: install node
            inputs:
              versionSpec: '6.x'
              checkLatest: true
          - task: Npm@1
            displayName: npm install
            inputs:
              command: 'install'
          - task: Bash@3
            displayName: build server
            inputs:
              targetType: 'inline'
              script: |
                tsc
                ls
          - task: ArchiveFiles@2
            displayName: archive server build
            inputs:
              rootFolderOrFile: 'dist'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            displayName: publish artifact
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'